naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: bi91HdKDkR9qosGQu11Q
    secret: ZlfJXY2mOk


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodiefinds
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show-sql: true
    defer-datasource-initialization: true